### ISSUE TITLE
Missing Option 112 - Maximum Z Feed Rate on Ocotoprint Plugin Installation

### ISSUE THREAD

**Issue by phalix** [synman/Octoprint-Bettergrblsupport#82]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_bettergrblsupport/__init__.py", line 1412, in on_api_command
    zf = int(float(self.grblSettings.get(112)[0]))

I found then, that in the Config.yaml of octoprint, the 112 is not in the grblsettingstext.

The issue is fixed when manually editing the config yaml in the octoprint folder.

**Comment by synman** [comment]
I sense I may be taking this on soon as I have a GRBL ESP32 machine I'm in the process of bringing online.  The reason why it is failing is because the official version of GRBL doesn't have a $113 setting (the settings array is base 0 so 112 internally is actually $113):

https://github.com/gnea/grbl/blob/master/doc/markdown/settings.md
